language: python
python:
  - '2.7'
services:
# command to install dependencies
install: 
  - 'easy_install -U setuptools'
  - 'pip install -U pip'
  - 'pip install -e .[tests]'
# command to run tests
script: 
  - 'py.test -sv --cov-report term-missing --cov msg_router tests'
  - 'pip install flake8 --use-mirrors'
  - 'flake8 msg_router --ignore=E501,W293'
